# Numpy Basics

<b>Angel Grace R. Macawili</b>
<br>Computer Engineering Technology

In [7]:
# imports and packages
import numpy as np
from scipy import stats
from statistics import multimode

# 1D Array

In [8]:
my_array = np.array([1,2,3])
my_array

array([1, 2, 3])

In [9]:
np.shape(my_array)

(3,)

# 2D Array

In [10]:
my_array = np.array([
    [1,2,3],
    [4,5,6]
])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
np.shape(my_array)

(2, 3)

In [12]:
t_array = my_array.T
t_array

array([[1, 4],
       [2, 5],
       [3, 6]])

# Measures of Central Tendency

In [13]:
#Jaguar vs Panther
resistance = np.array ([
    [10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8],
    [10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1, np.nan]
])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [14]:
np.shape(resistance)

(2, 11)

In [15]:
np.mean(resistance, axis=1)

array([9.4, nan])

In [16]:
np.nanmean(resistance, axis=1)

array([ 9.4 , 10.75])

In [17]:
res_mean = np.nanmean(resistance, axis=1)
res_mean

array([ 9.4 , 10.75])

In [18]:
print(f'Jaguar Mean: {res_mean[0]:.2f}ohms')
print(f'Panther Mean: {res_mean[1]:.2f}ohms')

Jaguar Mean: 9.40ohms
Panther Mean: 10.75ohms


In [19]:
#median
res_median = np.nanmedian(resistance, axis=1)
res_median

array([9.8 , 9.55])

In [20]:
#mode
res_mode = stats.mode(resistance, axis=1)
res_mode

ModeResult(mode=array([9.8, 9.1]), count=array([2., 3.]))

In [21]:
jag_res = resistance[0]

print ("Jaguar Mode:")
for i in multimode(jag_res):
    print (f'{i} ohms')

Jaguar Mode:
9.8 ohms
10.4 ohms


In [22]:
pan_res = resistance[1]

print ("Panther Mode:")
for i in multimode(pan_res):
    print (f'{i} ohms')

Panther Mode:
9.1 ohms


# Measures of Variability

In [23]:
# Jaguar vs Panther
resistance = np.array([
    [10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8],
    [10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1,np.nan]
])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [24]:
#Range
res_max = np.nanmax(resistance, axis=1)
res_min = np.nanmin(resistance, axis=1)

res_range = res_max - res_min
res_range

array([ 8. , 10.9])

In [25]:
print(f'Jaguar Range: {res_range[0]:.2f} ohms')
print(f'Panther Range: {res_range[1]:.2f} ohms')

Jaguar Range: 8.00 ohms
Panther Range: 10.90 ohms


In [26]:
res_Q1 = np.nanpercentile(resistance,25,axis=1)
res_Q1

array([9.4  , 9.125])

In [27]:
res_Q3 = np.nanpercentile(resistance,75,axis=1)
res_Q3

array([10.45 , 10.625])

In [28]:
print(f'Jaguar IQR: {res_Q3[0] - res_Q1[0]:.2f} ohms')
print(f'Panther IQR: {res_Q3[1]- res_Q1[1]:.2f} ohms')

Jaguar IQR: 1.05 ohms
Panther IQR: 1.50 ohms


In [29]:
res_var = np.nanvar(resistance,ddof=1,axis=1)
res_var

array([ 4.86      , 11.08277778])

In [30]:
print(f'Jaguar Variance: {res_var[0]:.2f} ohms')
print(f'Panther Variance: {res_var[1]:.2f} ohms')

Jaguar Variance: 4.86 ohms
Panther Variance: 11.08 ohms


In [31]:
res_std = np.nanstd (resistance, ddof=1, axis=1)

print(f'Jaguar Range: {res_std[0]:.2f} ohms')
print(f'Panther Range: {res_std[1]:.2f} ohms')

Jaguar Range: 2.20 ohms
Panther Range: 3.33 ohms
